-- Generated by level_export.py from Blender 2.49
-- Copyright 2011 Nigel Atkinson.  See LICENSE file for license.

local level = {}
level.meshes = {}
level.cameras = {}
level.points = {}
local mesh, camera, point
-------------

mesh = {}
mesh.name = 'Bridge_walk2'
mesh.filename = 'Bridge_walk.mesh'
mesh.loc = { -256.0, 0.0, 96.0 }
mesh.rot = { 0.70710682869, 0.0, -0.70710682869, -0.0 }
mesh.scale = { 1.0, 1.0, 1.0 }
level.meshes[mesh.name] = mesh
-------------

mesh = {}
mesh.name = 'Island_walk'
mesh.filename = 'Island_walk.mesh'
mesh.loc = { 0.0, 0.0, -0.0 }
mesh.rot = { 1.0, 0.0, 0.0, -0.0 }
mesh.scale = { 1.0, 1.0, 1.0 }
level.meshes[mesh.name] = mesh
-------------

mesh = {}
mesh.name = 'Bridge2'
mesh.filename = 'Bridge.mesh'
mesh.loc = { -256.0, 0.0, 96.0 }
mesh.rot = { 0.70710682869, 0.0, -0.70710682869, -0.0 }
mesh.scale = { 1.0, 1.0, 1.0 }
level.meshes[mesh.name] = mesh
mesh.isEntity = true
mesh.walkmesh = 'Bridge_walk2'
-------------

mesh = {}
mesh.name = 'Bridge1'
mesh.filename = 'Bridge.mesh'
mesh.loc = { -32.0, 0.0, -96.0 }
mesh.rot = { 1.0, 0.0, 0.0, -0.0 }
mesh.scale = { 1.0, 1.0, 1.0 }
level.meshes[mesh.name] = mesh
mesh.isEntity = true
mesh.walkmesh = 'Bridge_walk1'
-------------

mesh = {}
mesh.name = 'Island'
mesh.filename = 'Island.mesh'
mesh.loc = { 0.0, 0.0, -0.0 }
mesh.rot = { 1.0, 0.0, 0.0, -0.0 }
mesh.scale = { 1.0, 1.0, 1.0 }
level.meshes[mesh.name] = mesh
mesh.isEntity = true
mesh.walkmesh = 'Island_walk'
-------------

mesh = {}
mesh.name = 'Bridge_walk1'
mesh.filename = 'Bridge_walk.mesh'
mesh.loc = { -32.0, 0.0, -96.0 }
mesh.rot = { 1.0, 0.0, 0.0, -0.0 }
mesh.scale = { 1.0, 1.0, 1.0 }
level.meshes[mesh.name] = mesh
-------------

mesh = {}
mesh.name = 'StreetLamp'
mesh.filename = 'StreetLamp.mesh'
mesh.loc = { 64.0, 80.0, -0.0 }
mesh.rot = { 1.0, 0.0, 0.0, -0.0 }
mesh.scale = { 1.0, 1.0, 1.0 }
level.meshes[mesh.name] = mesh
mesh.isEntity = true
-------------

camera={}
camera.name = 'Camera_001'
camera.loc = { 356.0, 116.0, -326.0 }
camera.rot = { 0.323744416237, 0.271653831005, 0.694272041321, -0.582563400269 }
level.cameras[camera.name] = camera
-------------

point={}
point.name = 'player_spawn'
point.loc = { -139.24432373, 0.206147372723, 271.409637451 }
point.rot = { 0.819152057171, 0.0, 0.573576450348, -0.0 }
level.points[point.name] = point
point.spawn = 'Robot'
-------------

return level
